name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Initialise environment for ${{ github.ref }}
        shell: pwsh
        run: |
          $out = git rev-list ed734fd9.. --count
          echo "VER=4.$out" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: dotnet publish
        run: |
          dotnet publish --configuration Release -p:Version=${{env.VER}} -p:FileVersion=${{env.VER}} -p:AssemblyVersion=${{env.VER}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OldFiles-v${{env.VER}}
          path: |
            Builds/Release-publish/
          if-no-files-found: error
